# encoding: utf-8
from __future__ import unicode_literals

# Generated by Django 2.0.4 on 2018-04-29 05:40
from django.db import migrations, models
from django.contrib.auth.admin import User
import django.db.models.deletion
import datetime

def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.net'
    superuser.set_password('admin')
    superuser.last_login=datetime.datetime.now()
    superuser.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            create_superuser
        ),
    ]
