# Generated by Django 2.0.6 on 2018-06-26 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='sin-imagen/no-img.jpg', upload_to='padrinos/%Y/%m/%d')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('agasajado', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('foto_principal', models.ImageField(default='sin-imagen/no-img.jpg', upload_to='principal/%Y/%m/%d')),
                ('foto_secundaria', models.ImageField(default='sin-imagen/no-img.jpg', upload_to='secundaria/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='sin-imagen/no-img.jpg', upload_to='padrinos/%Y/%m/%d')),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizador', to='app.Organizador'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Evento'),
        ),
    ]
