# Generated by Django 2.0.7 on 2018-07-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180626_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitado',
            old_name='apellido',
            new_name='nombre_apellido',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='nombre',
        ),
    ]
